---
x-general: &general
  init: true
  restart: unless-stopped
  env_file:
    - path: default.env
      required: false
  labels:
    - autoheal=true
    - com.centurylinklabs.watchtower.enable=true

x-healthcheck: &healthcheck
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3

name: wallos

services:
  wallos:
    <<: [*general, *healthcheck]
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    # Volumes store your data between container upgrades
    volumes:
      - /mnt/docker-data/wallos/db:/var/www/html/db
      - /mnt/docker-data/wallos/logos:/var/www/html/images/uploads/logos
