---
x-general: &general
  init: true
  restart: unless-stopped
  env_file:
    - path: default.env
      required: false
  labels:
    - autoheal=true
    - com.centurylinklabs.watchtower.enable=true

x-healthcheck: &healthcheck
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3

name: cloudflare-ddns

services:
  cloudflare-ddns:
    <<: [*general, *healthcheck]
    container_name: cloudflare-ddns
    hostname: cloudflare-ddns
    image: oznu/cloudflare-ddns:latest
    env_file:
      - path: default.env
        required: true
      - path: cloudflare.env
        required: true

  cloudflare-ddns2:
    <<: [*general, *healthcheck]
    container_name: cloudflare-ddns2
    hostname: cloudflare-ddns2
    image: oznu/cloudflare-ddns:latest
    env_file:
      - path: default.env
        required: true
      - path: cloudflare2.env
        required: true
