---
x-general: &general
  restart: unless-stopped
  labels:
    - autoheal=true
  #healthcheck:
  #  test: curl google.com || exit 1
  #  interval: 30s
  #  timeout: 10s
  #  retries: 3
  init: true
  env_file:
    - path: default.env
      required: true

name:  minecraft

services:
  minecraft:
    <<: [ *general ]
    container_name: minecraft
    hostname: minecraft
    image: itzg/minecraft-server 
    ports:
      - 25565:25565
    environment:
      - TYPE=PAPER
      - INIT_MEMORY=1G
      - MAX_MEMORY=4G
      - EULA=TRUE
      - ENABLE_AUTOPAUSE=TRUE
      - AUTOPAUSE_TIMEOUT_EST=300
      - AUTOPAUSE_TIMEOUT_INIT=300
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/Docker/container-data/minecraft-paper/data:/data

