---
x-general: &general
  init: true
  restart: unless-stopped
  env_file:
    - path: default.env
      required: false
  labels:
    - autoheal=true
    - com.centurylinklabs.watchtower.enable=true

x-healthcheck: &healthcheck
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3

name: homepage

services:
  homepage:
    <<: [*general]
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    user: 1000:1000
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/disk3/DockerData/homepage/config:/app/config
      #- /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: 1000
      PGID: 1000
