---
x-general: &general
#  restart: unless-stopped
  labels:
    - autoheal=true
#  healthcheck:
#    test: curl google.com || exit 1
#    interval: 30s
#    timeout: 10s
#    retries: 3
#  init: true
#  env_file:
#    - path: default.env
#      required: true

name: watchtower
services:
  watchtower:
    <<: [*general]
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
