---
x-general: &general
  restart: unless-stopped
  labels:
    - autoheal=true
    - "com.centurylinklabs.watchtower.enable=true"
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3
  init: true
  env_file:
    - path: default.env
      required: true

name: nginx-site-personal

services:
  nginx-site-personal:
    <<: [*general]
    container_name: nginx-site-personal
    hostname: nginx-site-personal
    image: nginx
    ports:
      - 8000:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /nfs/3/DockerData/nginx-sites/personal-site:/usr/share/nginx/html:ro
    environment:
      - PUID=1002
      - PGID=1003
