---
x-general: &general
  init: true
  restart: unless-stopped
  env_file:
    - path: default.env
      required: false
  labels:
    - autoheal=true
    - com.centurylinklabs.watchtower.enable=true

x-healthcheck: &healthcheck
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3

name: nginx-site-personal

services:
  nginx-site-personal:
    <<: [*general, *healthcheck]
    container_name: nginx-site-personal
    hostname: nginx-site-personal
    image: nginx
    ports:
      - 8000:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-data/nginx-sites/personal-site:/usr/share/nginx/html:ro
    environment:
      - PUID=1003
      - PGID=1003
