---
x-general: &general
  init: true
  restart: unless-stopped
  env_file:
    - path: default.env
      required: false
  labels:
    - autoheal=true
    - com.centurylinklabs.watchtower.enable=true

x-healthcheck: &healthcheck
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3

x-vikunja: &vikunja
  env_file:
    - path: default.env
      required: false
    - path: vikunja.env
      required: true

name: vikunja

services:
  vikunja:
    <<: [*general, *vikunja]
    container_name: vikunja
    hostname: vikunja
    image: vikunja/vikunja
    ports:
      - 3456:3456
    #healthcheck:
    #  test: wget --no-verbose --tries=1 --spider http://localhost:3456 || exit 1
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/disk3/DockerData/vikunja/files:/app/vikunja/files
    depends_on:
      vikunja-db:
        condition: service_healthy

  vikunja-db:
    <<: [*general, *vikunja]
    container_name: vikunja-db
    hostname: vikunja-db
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/disk3/DockerData/vikunja/db:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD",
        ]
      interval: 2s
      start_period: 30s
