---
x-general: &general
  restart: unless-stopped
  labels:
    - autoheal=true
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3
  env_file:
    - path: default.env
      required: true

name:  jellyfin

services:
  jellyfin:
    <<: [ *general ]
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=1002
      - PGID=1002
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/Docker/container-data/jellyfin/config:/config:rw
      - /mnt/MediaLibrary1:/data/library1:ro
      - /mnt/MediaLibrary2:/data/library2:ro
    ports:
      - 8096:8096
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
