---
x-general: &general
  restart: unless-stopped
  labels:
    - autoheal=true
  #healthcheck:
  #  test: curl google.com || exit 1
  #  interval: 30s
  #  timeout: 10s
  #  retries: 3
  init: true
  env_file:
    - path: default.env
      required: true

x-minecraft: &minecraft
  image: marctv/minecraft-papermc-server
  environment:
    - TYPE=PAPER
    - INIT_MEMORY=128M
    - MAX_MEMORY=4G
    - EULA=TRUE
   # - ENABLE_AUTOPAUSE=TRUE
   # - AUTOPAUSE_TIMEOUT_EST=300
   # - AUTOPAUSE_TIMEOUT_INIT=300

name: minecraft

services:
  velocity:
    <<: [*general]
    container_name: velocity
    image: treysu/velocity:latest
    ports:
      - 25577:25577
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/Docker/container-data/velocity/data:/data
      #- /mnt/disk3/DockerData/velocity/data:/data
    environment:
      - PUID=1002
      - PGID=1003
    depends_on:
      minecraft-toh:
        condition: service_started
      #minecraft-skyblock:
      #  condition: service_started
      #minecraft-lobby:
      #  condition: service_started

#  minecraft-lobby:
#    <<: [*general, *minecraft]
#    container_name: minecraft-lobby
#    ports:
#      - 25590:25565
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /mnt/disk3/DockerData/minecraft-lobby/data:/data
#
#  minecraft-survival:
#    <<: [*general, *minecraft]
#    container_name: minecraft-survival
#    ports:
#      - 25591:25565
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /mnt/disk3/DockerData/minecraft-survival/data:/data
#
#  minecraft-skyblock:
#    <<: [*general, *minecraft]
#    container_name: minecraft-skyblock
#    ports:
#      - 25592:25565
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /mnt/disk3/DockerData/minecraft-skyblock/data:/data
#
#  minecraft-creative:
#    <<: [*general, *minecraft]
#    container_name: minecraft-creative
#    ports:
#      - 25593:25565
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /mnt/disk3/DockerData/minecraft-creative/data:/data

  minecraft-toh:
    <<: [*general, *minecraft]
    container_name: minecraft-toh
    ports:
      - 25594:25565
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/disk3/DockerData/minecraft-toh/data:/data

