---
x-general: &general
  #init: true
  restart: unless-stopped
  env_file:
    - path: default.env
      required: false
  labels:
    - autoheal=true
    - com.centurylinklabs.watchtower.enable=true

x-healthcheck: &healthcheck
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3

x-automation: &automation
  environment:
    - PUID=1000
    - PGID=1000

name: homeassistant

services:
  #-------------------------------------
  frigate:
    <<: [*general, *healthcheck]
    container_name: frigate
    hostname: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # Passes PCIe Coral
      - /dev/dri:/dev/dri # Passes PCIe GPU for transcoding
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/Docker/container-data/frigate/config:/config
      #- /mnt/disk3/DockerData/frigate/config:/config
      - /mnt/disk3/Frigate:/media/frigate

    ports:
      - "5000:5000"
      - "8556:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    #environment:
    #  LIBVA_DRIVER_NAME: "radeonsi"

    cap_add:
      - CAP_PERFMON
    env_file:
      - path: default.env
        required: true
      - path: frigate.env
        required: true
