---
x-general: &general
  restart: unless-stopped
  labels:
    - autoheal=true
    - "com.centurylinklabs.watchtower.enable=true"
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3
  user: 1000:1000
  init: true
  #environment:
    #- PUID=1000
    #- PGID=1000
  env_file:
    - path: default.env
      required: true

name: uptime-kuma

services:
  uptime-kuma:
    <<: [*general]
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma:1
    ports:
      - 3101:3001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nfs_volume:/app/data


volumes:
  nfs_volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.101.56,nolock,soft,rw  # Replace with your NFS server address and options
      device: ":/mnt/disk3/DockerData/uptime-kuma"  # Replace with your NFS share path

