---
x-general: &general
  init: true
  restart: unless-stopped
  env_file:
    - path: default.env
      required: false
  labels:
    - autoheal=true
    - com.centurylinklabs.watchtower.enable=true

x-healthcheck: &healthcheck
  healthcheck:
    test: curl google.com || exit 1
    interval: 30s
    timeout: 10s
    retries: 3

name: uptime-kuma

services:
  uptime-kuma:
    <<: [*general, *healthcheck]
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma:1
    ports:
      - 3101:3001
    user: 1000:1000
    #environment:
    #- PUID=1000
    #- PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/disk3/DockerData/uptime-kuma:/app/data
